export const data = [
  {
    id: 1,
    title: "HTML",
    category: "frontend",
    image: "/skills-images/HTML.png",
  },
  {
    id: 2,
    title: "CSS",
    category: "frontend",
    image: "/skills-images/CSS.png",
  },
  {
    id: 3,
    title: "Bootstrap",
    category: "frontend",
    image: "/skills-images/Bootstrap.avif",
  },
  {
    id: 4,
    title: "Tailwind.CSS",
    category: "frontend",
    image: "/skills-images/Tailwind-CSS.png",
  },
  {
    id: 5,
    title: "JavaScript",
    category: "frontend",
    image: "/skills-images/JS.webp",
  },
  {
    id: 6,
    title: "TypeScript",
    category: "frontend",
    image: "/skills-images/TS.jpg",
  },
  {
    id: 7,
    title: "React.JS",
    category: "frontend",
    image: "/skills-images/React.jpg",
  },
  {
    id: 8,
    title: "Material UI",
    category: "frontend",
    image: "/skills-images/MUI.png",
  },
  {
    id: 9,
    title: "Next.JS",
    category: "frontend",
    image: "/skills-images/NextJS.webp",
  },
  {
    id: 10,
    title: "Angular",
    category: "frontend",
    image: "/skills-images/Angular.jpg",
  },
  {
    id: 11,
    title: "Node.JS",
    category: "backend",
    image: "/skills-images/NodeJS.png",
  },
  {
    id: 12,
    title: "Express.JS",
    category: "backend",
    image: "/skills-images/ExpressJS.jpg",
  },
  {
    id: 13,
    title: "Nest.JS",
    category: "backend",
    image: "/skills-images/NestJS.png",
  },
  {
    id: 14,
    title: "Mongo DB",
    category: "backend",
    image: "/skills-images/MongoDB.png",
  },
  {
    id: 15,
    title: "PostgreSql",
    category: "backend",
    image: "/skills-images/Postgresql.jpg",
  },
  {
    id: 16,
    title: "Git",
    category: "version-control",
    image: "/skills-images/Git.jpg",
  },
  {
    id: 17,
    title: "GitHub",
    category: "version-control",
    image: "/skills-images/GitHub.jpg",
  },
];
